/*1*/ SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' Order by apellido1, apellido2, nombre;
/*2*/ SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' AND telefono is NULL;
/*3*/ SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'alumno' AND EXTRACT(YEAR FROM fecha_nacimiento) = 1999;
/*4*/ SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = 'profesor' AND telefono is NULL AND nif LIKE '%K%';
/*5*/ SELECT nombre, cuatrimestre, curso, id_grado FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
/*6*/ SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre FROM persona INNER JOIN profesor On persona.id = profesor.id_profesor INNER JOIN departamento On departamento.id = profesor.id_departamento WHERE persona.tipo = 'profesor' Order by persona.apellido1, persona.apellido2, persona.nombre ASC;
/*7*/ SELECT asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM asignatura INNER JOIN alumno_se_matricula_asignatura On asignatura.id = alumno_se_matricula_asignatura.id_asignatura INNER JOIN curso_escolar On curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar INNER JOIN persona On persona.id = alumno_se_matricula_asignatura.id_alumno WHERE persona.nif = '26902806M';
/*8*/ SELECT DISTINCT departamento.nombre FROM departamento INNER JOIN profesor On departamento.id = profesor.id_departamento INNER JOIN asignatura On profesor.id_profesor = asignatura.id_profesor INNER JOIN grado On asignatura.id_grado = grado.id WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)'; 
/*9*/ SELECT DISTINCT persona.apellido1, persona.apellido2, persona.nombre FROM persona INNER JOIN alumno_se_matricula_asignatura On persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN curso_escolar On alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE curso_escolar.anyo_inicio = 2018 AND curso_escolar.anyo_fin = 2019;

/*consultes utilitzant les clàusules LEFT JOIN i RIGHT JOIN*/
/*1*/ SELECT departamento.nombre AS 'nombre departamento', persona.apellido1, persona.apellido2, persona.nombre FROM persona RIGHT JOIN profesor On persona.id = profesor.id_profesor RIGHT JOIN departamento On profesor.id_departamento = departamento.id WHERE persona.tipo = 'profesor' ORDER by departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre Asc;
/*2*/ SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre AS 'nombre departamento' FROM persona LEFT JOIN profesor On persona.id = profesor.id_profesor LEFT JOIN departamento On profesor.id_departamento = departamento.id WHERE persona.tipo = 'profesor' AND departamento.id_profesor is Null;
/*3*/ SELECT persona.apellido1, persona.apellido2, persona.nombre, departamento.nombre AS 'nombre departamento' FROM persona RIGHT JOIN profesor On persona.id = profesor.id_profesor RIGHT JOIN departamento On profesor.id_departamento = departamento.id WHERE persona.tipo = 'profesor' AND departamento.id_profesor is Null;
/*4*/ SELECT persona.apellido1, persona.apellido2, persona.nombre, asignatura.id_profesor AS 'Asignatura' FROM persona LEFT JOIN profesor On persona.id = profesor.id_profesor LEFT JOIN asignatura On profesor.id_profesor = asignatura.id_profesor WHERE persona.tipo = 'profesor' AND asignatura.id_profesor Is Null;
/*5*/ SELECT asignatura.nombre, asignatura.id_profesor FROM asignatura LEFT JOIN profesor On asignatura.id_profesor = profesor.id_profesor WHERE asignatura.id_profesor Is Null;
/*6*/ SELECT DISTINCT departamento.nombre FROM departamento LEFT JOIN profesor On departamento.id = profesor.id_departamento LEFT JOIN asignatura On profesor.id_profesor = asignatura.id_profesor where asignatura.curso Is Null;

/*Consultes resum*/
/*1*/ SELECT COUNT(tipo) As 'Total alumnas' FROM persona WHERE tipo = 'alumno';
/*2*/ SELECT COUNT(tipo) AS 'Alumnos nacidos en 1999' FROM persona WHERE tipo = 'alumno' AND EXTRACT(YEAR FROM fecha_nacimiento) = 1999;
/*3*/ SELECT departamento.nombre AS 'Nombre departamento', COUNT(profesor.id_profesor) AS 'Numero profesores' FROM departamento INNER JOIN profesor On departamento.id = profesor.id_departamento GROUP BY departamento.nombre ORDER by `Numero profesores` Desc;
/*4*/ SELECT departamento.nombre AS 'Nombre departamento', COUNT(profesor.id_profesor) AS 'Numero profesores' FROM departamento LEFT JOIN profesor On departamento.id = profesor.id_departamento GROUP BY departamento.nombre;
/*5*/ SELECT grado.nombre AS 'Nombre de grado', COUNT(asignatura.id_grado) AS 'Numero asignaturas' FROM grado LEFT JOIN asignatura On grado.id = asignatura.id_grado GROUP BY grado.nombre ORDER by `Numero asignaturas` desc;
/*6*/ SELECT grado.nombre AS 'Nombre de grado', COUNT(asignatura.id_grado) AS 'Numero asignaturas' FROM grado LEFT JOIN asignatura On grado.id = asignatura.id_grado GROUP BY grado.nombre  HAVING COUNT('Numero asignaturas') > 40;
/*7*/ SELECT grado.nombre AS 'Nombre de grado', asignatura.tipo AS 'Tipo asignatura', SUM(asignatura.creditos) AS 'Suma creditos' FROM grado RIGHT JOIN asignatura On grado.id = asignatura.id_grado GROUP BY asignatura.tipo, grado.nombre;
/*8*/ SELECT curso_escolar.anyo_inicio AS 'Anio inicio escolar', COUNT(DISTINCT alumno_se_matricula_asignatura.id_alumno) AS 'Alumnas matriculadas' FROM curso_escolar INNER JOIN alumno_se_matricula_asignatura On curso_escolar.id = alumno_se_matricula_asignatura.id_curso_escolar GROUP by curso_escolar.anyo_inicio;
/*9*/ SELECT persona.id, persona.apellido1, persona.apellido2, persona.nombre, COUNT(asignatura.id) AS 'Numero asignaturas' FROM persona LEFT JOIN asignatura On persona.id = asignatura.id_profesor WHERE persona.tipo = 'profesor' GROUP by persona.id, persona.apellido1, persona.apellido2, persona.nombre Order by asignatura.id Desc;
/*10*/ SELECT * FROM persona WHERE tipo = 'alumno' Order by fecha_nacimiento Desc Limit 1;
/*11*/ SELECT persona.apellido1, persona.apellido2, persona.nombre, asignatura.nombre AS 'Nombre Asignatura' FROM persona LEFT JOIN profesor On persona.id = profesor.id_profesor LEFT JOIN asignatura On profesor.id_profesor = asignatura.id_profesor Where persona.tipo = 'profesor' AND asignatura.id_profesor Is Null;